## 인덱싱



*   1차원 배열의 인덱싱



In [ ]:
import numpy as np

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5])

print(a[0], a[3], a[5])

0 3 5




*   2차원 배열의 인덱싱



In [ ]:
a = np.array([[ 0, 1, 2 ],
              [ 3, 4, 5 ],
              [ 6, 7, 8 ]])
print(a[2,2])             # 2행 2열   출력결과 : 8
print(a[0,0])             # 0행 0열   출력결과 : 0
print(a[1,2])             # 1행 2열   출력결과 : 5
print(a[-2,2])            # -2행(뒤에서 두번째) 3열
print(a[-3,-1])           #-3행(뒤에서 세번째) -1열(가장 마지막)

8
0
5
5
2


## 슬라이싱



*   1차원 배열의 슬라이싱



In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6])
print(a[1:3])
print(a[:3])
print(a[:-1])
print(a[2:-1])

[1 2]
[0 1 2]
[0 1 2 3 4 5]
[2 3 4 5]




*   2차원 배열의 슬라이싱



In [ ]:
a = np.array([
    [1, 2, 3, 4, 5 ],
    [ 6, 7, 8, 9, 10 ],
    [ 11, 12, 13, 14, 15]
    ])
print(a[1,1:3])
print(a[1:2,1])
print(a[1:2,:])
print(a[:2,2:4])
print(a[:3,1:3])

[7 8]
[7]
[[ 6  7  8  9 10]]
[[3 4]
 [8 9]]
[[ 2  3]
 [ 7  8]
 [12 13]]


## 자유자재로 인덱싱 해보기



*   배열 인덱싱 기본 (불리언 / 정수)



In [ ]:
a = np.array([0, 1, 2, 3, 4, 5])
a > 3

array([False, False, False, False,  True,  True])

In [ ]:
a[a>3]

array([4, 5])

In [ ]:
a[ (a>3) & (a%2 == 0)]

array([4])

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array([False, True, False, True, False, True])
a[b]

array([1, 3, 5])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a_index = np.array([1, 4, 1, 2, 3, 2, 0, 1])
a[a_index]


array([2, 5, 2, 3, 4, 3, 1, 2])

In [ ]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

In [ ]:
a[[ 2, 1, 0] , :]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [ ]:
a[[2, 1] , :]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a[: , [0,-1]]

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])



*   배열 인덱싱 활용 (불리언 / 정수)


In [ ]:
name = np.array(['정','정','김','이', '김'])
char = np.array([[ 10, 11, 12, 13, 14 ] ,
                 [ 20, 21, 22, 23, 24 ] ,
                 [ 30, 31, 32, 33, 34 ] ,
                 [ 40, 41, 42, 43, 44 ] ,
                 [ 50, 51, 52, 53, 54 ]])

In [ ]:
name =='정'

array([ True,  True, False, False, False])

In [ ]:
char[: , name=='정' ]

array([[10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51]])

In [ ]:
char[name =='정',:]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [ ]:
char [ (name == '정') | (name =='이') , : ]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [40, 41, 42, 43, 44]])

## 해당 코드는 wikidocs의 코드를 참고하였습니다.
## https://wikidocs.net/193542