## 넘파이 임포트

In [ ]:
import numpy as np

## 넘파이 데이터 타입

In [ ]:
a = np.array([1, 2, 3, 3, 4])
a

array([1, 2, 3, 3, 4])

In [ ]:
b = np.array([1, 2.3, 3, 4])
b

array([1. , 2.3, 3. , 4. ])

In [ ]:
c = np.array([1, '2', '3', 4])
c

array(['1', '2', '3', '4'], dtype='<U21')

In [ ]:
d = np.array([1, 2, 3, 4])
print(type(d))

<class 'numpy.ndarray'>


## 배열을 만드는 3가지 방법

## array(시퀀스 자료형)으로 직접 만들기



*   1차원 배열 만들기



In [ ]:
e = np.array([1, 2, 3, 4])
e

array([1, 2, 3, 4])



*   2차원 배열 만들기



In [ ]:
f = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
f

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 행의 갯수 구하기
print(len(f))

# 열의 갯수 구하기
print(len(f[0]))

2
4


## 기본값이 있는 배열 만들기



*   0으로 채워져 있는 배열 만들기




In [ ]:
a = np.zeros(10, dtype=np.int8)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)



*   0으로 채워져 있는 Matrix(2차원 배열)만들기



In [ ]:
a = np.zeros((2, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]




*   1로 채워져 있는 배열 만들기



In [ ]:
a = np.ones(5, dtype=np.int8)
a

array([1, 1, 1, 1, 1], dtype=int8)

In [ ]:
a = np.ones((2, 5), dtype=np.int8)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

## 연속된 값이 있는 배열 만들기



*   연속되며 증가되는 수열 만들기


In [ ]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a = np.arange(1, 9, 3)
a

array([1, 4, 7])



*   범위를 정해주고 정해진 수만큼 분할된 수열 만들기


In [ ]:
a = np.linspace(0, 100, 5, dtype=np.int32)
a

array([  0,  25,  50,  75, 100], dtype=int32)

## 배열의 차원과 크기 알아내기

In [ ]:
a1 = np.array( [ 1, 2, 3, 4, 5 ])
a2 = np.array( [ [ 1, 2, 3, 4 ] , [ 1, 2, 3, 4 ] ] )
a3 = np.array( [ [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                     [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                     [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ] )




*   배열의 차원 알아내기



In [ ]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3




*   배열의 크기 알아내기



In [ ]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(2, 4)
(3, 2, 3)


## 배열의 차원 바꾸기

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = a.reshape(2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = a.reshape(5,-1)   #5행으로 만들어줘 열은 잘 모름
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## 행과 열을 바꾸기

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = a.T
b

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열 연결하기



*   같은 행 배열 연결하기



In [ ]:
a = np.array([
    [1, 2],
    [4, 5]
])
b = np.array([
    [0, 0, 0],
    [0, 0, 0]
])

np.hstack([a, b])

array([[1, 2, 0, 0, 0],
       [4, 5, 0, 0, 0]])



*   같은 열 배열 연결하기



In [ ]:
a = np.array([1, 2, 3, 4 ])
b = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])
np.vstack( [a, b ])

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 해당 코드는 wikidocs의 코드를 참고하였습니다.
## https://wikidocs.net/193542