## 넘파이 연산





*   배열 하나로 쉽게 연산하기



In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a + 2

array([3, 4, 5, 6, 7])

In [ ]:
a * 2

array([ 2,  4,  6,  8, 10])



*   배열 두개로 쉽게 연산하기



In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
c = a + b
c

array([5, 7, 9])

In [ ]:
c = 2 + 5 * b - a
c

array([21, 25, 29])



*   ==사용해보기



In [ ]:
c = np.array([21, 25, 29])
c == 25

array([False,  True, False])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

a == b

array([False,  True, False])

## 연산을 함수로 사용해보기(배열 두개)



*   더하기 add / 빼기 substract / 곱하기 multiply / 나누기 divide



In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

c1 = np.add(a, b)
c2 = np.subtract(a, b)
c3 = np.multiply(a, b)
c4 = np.divide(a, b)

print(c1)
print(c2)
print(c3)
print(c4)

[4 4 4]
[-2  0  2]
[3 4 3]
[0.33333333 1.         3.        ]




*   maximum 최대값 / minimum 최소 값


In [ ]:
a = np.array([2, 3, 4])
b = np.array([1, 5, 2])

c1 = np.maximum(a, b)
c2 = np.minimum(a, b)

print(c1)
print(c2)

[2 5 4]
[1 3 2]


## 원소들의 통계함수(배열 한개)



*   합계 sum / 누적합 cumsum / 곱 prod / 누적곱 cumprod



In [ ]:
a = np.array([1, 2, 3, 4, 5])

b1 = np.sum(a)
b2 = np.cumsum(a)
b3 = np.prod(a)
b4 = np.cumprod(a)

print(b1)
print(b2)
print(b3)
print(b4)

15
[ 1  3  6 10 15]
120
[  1   2   6  24 120]




*   평균 mean / 분산 var / 표준편차 std



In [ ]:
b1 = np.mean(a)
b2 = np.std(a)
b3 = np.var(a)

print(b1)
print(b2)
print(b3)

3.0
1.4142135623730951
2.0




*   최대값 max / 최소값 min



In [ ]:
b1 = np.max(a)
b2 = np.min(a)

print(b1)
print(b2)

5
1


## 중복 제거하기

In [ ]:
a = np.array([ 1, 1, 2, 3, 4, 5, 7, 7, 8, 5, 6, 8, 9, 10, 10])
a1 = np.unique(a)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


## 정렬함수



*   1차원배열 오름차순 / 내림차순 정렬



In [ ]:
a = np.array( [ 0.2548745, 0.0548778, 0.11547, 0.2548744, -1.215487 ] )

In [ ]:
b1 = np.sort(a)
b2 = np.sort(a)[::-1]

print(b1)
print(b2)

[-1.215487   0.0548778  0.11547    0.2548744  0.2548745]
[ 0.2548745  0.2548744  0.11547    0.0548778 -1.215487 ]




*   2차원배열 오름차순 / 내림차순 정렬



In [ ]:
a = np.array( [ [ 11, 5, 3 ],
                [ 2, 8, 9 ],
                [ 7, 3, 4] ] )

In [ ]:
b1 = np.sort(a, axis=0)     #행기준 정렬 3행의 모든 요소가 정렬
b2 = np.sort(a, axis=1)     #열기준 정렬 3열의 모든 요소가 정렬
print(b1)
print(b2)

[[ 2  3  3]
 [ 7  5  4]
 [11  8  9]]
[[ 3  5 11]
 [ 2  8  9]
 [ 3  4  7]]


## 해당 코드는 wikidocs의 코드를 참고하였습니다.
## https://wikidocs.net/193542